email:
  block:
    email: []
    username:
      - test
      - spam
      - fraud
    domain:
      - blocked.org
      - malware.com
    host:
      - banned
      - malicious
      - spam-host
    tld: []
