spring:
  config:
    import:
      - classpath:application-rest.yml
      - classpath:application-database.yml
      - classpath:application-configuration.yml
      - classpath:application-message.yml