spring:
  jackson: {}
  config:
    import:
      - classpath:application-restserver.yml
      - classpath:application-postgresql.yml
      - classpath:application-mongodb.yml
      - classpath:application-configuration.yml
      - classpath:application-rabbitmq.yml
      - classpath:application-handler-kafka.yml
