openapi: 3.0.3
info:
  version: 0.0.1
  title: Email API

tags:
  - name: emails
    description: Operations related to email block rules

servers:
  - url: http://localhost:8080/api

paths:
  /emails/blocks:
    $ref: './emails/emails-path.yml#/emails'
components:
  schemas:
    response:
      $ref: './common-schema.yml#/schemas/response'
    responseError:
      $ref: './common-schema.yml#/schemas/responseError'
