schemas:
  user:
    type: object
    properties:
      email:
        type: string
        format: email
      name:
        type: string
  userCreate:
    allOf:
      - $ref: './users-schema.yml#/schemas/user'
      - type: object
        required:
          - email
          - name
  userUpdate:
    allOf:
      - $ref: './users-schema.yml#/schemas/user'
      - type: object
        required:
          - email
          - name
  userPatch:
    allOf:
      - $ref: './users-schema.yml#/schemas/user'
  userRead:
    allOf:
      - $ref: './users-schema.yml#/schemas/user'
      - type: object
        required:
          - email
          - name
          - userId
        properties:
          userId:
            type: string
            format: uuid