user:
  parameters:
    - name: userUuid
      in: path
      required: true
      description: Uuid User value
      schema:
        type: string
        format: uuid
        nullable: false
  get:
    tags:
      - users
    summary: Get an User by Uuid
    operationId: getUserByUuid
    responses:
      '200':
        description: Expected response to a valid request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userResponse'
      '404':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '../common-schema.yml#/schemas/responseError'
      '500':
        description: Error
        content:
          application/json:
            schema:
              $ref: '../common-schema.yml#/schemas/responseError'
  delete:
    tags:
      - users
    summary: Delete an User by Uuid
    operationId: deleteUserByUuid
    responses:
      '200':
        description: Expected response to a valid request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userResponse'
      '404':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '../common-schema.yml#/schemas/responseError'
      '500':
        description: Error
        content:
          application/json:
            schema:
              $ref: '../common-schema.yml#/schemas/responseError'
  put:
    tags:
      - users
    summary: Update an User by Uuid
    operationId: updateUserByUuid
    requestBody:
      description: User Body value
      required: true
      content:
        application/json:
          schema:
            $ref: './users-schema.yml#/schemas/userUpdate'
    responses:
      '200':
        description: Expected response to a valid request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userResponse'
      '404':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '../common-schema.yml#/schemas/responseError'
      '500':
        description: Error
        content:
          application/json:
            schema:
              $ref: '../common-schema.yml#/schemas/responseError'
  patch:
    tags:
      - users
    summary: Patch an User by Uuid
    operationId: patchUserByUuid
    requestBody:
      description: Partial User Body value
      required: true
      content:
        application/json:
          schema:
            $ref: './users-schema.yml#/schemas/userPatch'
    responses:
      '200':
        description: Expected response to a valid request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userResponse'
      '404':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '../common-schema.yml#/schemas/responseError'
      '500':
        description: Error
        content:
          application/json:
            schema:
              $ref: '../common-schema.yml#/schemas/responseError'

users:
  get:
    tags:
      - users
    summary: Get all Users
    operationId: getAllUsers
    responses:
      '200':
        description: Expected response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/usersResponse'
      '500':
        description: Error
        content:
          application/json:
            schema:
              $ref: '../common-schema.yml#/schemas/responseError'
  post:
    tags:
      - users
    summary: Create an User
    operationId: createUser
    requestBody:
      description: User Body value
      required: true
      content:
        application/json:
          schema:
            $ref: './users-schema.yml#/schemas/userCreate'
    responses:
      '200':
        description: Expected response to a valid request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userResponse'
      '500':
        description: Error
        content:
          application/json:
            schema:
              $ref: '../common-schema.yml#/schemas/responseError'


components:
  schemas:
    userResponse:
      allOf:
        - $ref: '../common-schema.yml#/schemas/response'
        - type: object
          properties:
            data:
              $ref: './users-schema.yml#/schemas/userRead'
    usersResponse:
      allOf:
        - $ref: '../common-schema.yml#/schemas/response'
        - type: object
          properties:
            data:
              type: array
              uniqueItems: true
              items:
                $ref: './users-schema.yml#/schemas/userRead'